Update Terraform_single_button.yml

diff --git a/.github/workflows/Terraform_single_button.yml b/.github/workflows/Terraform_single_button.yml
--- a/.github/workflows/Terraform_single_button.yml
+++ b/.github/workflows/Terraform_single_button.yml
@@ -17,13 +17,19 @@ on:
         default: false
 
 jobs:
+  validate-inputs:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Validate inputs
+        run: |
+          if [[ "${{ inputs.deploy }}" == "code-deploy" && "${{ inputs.terraform_delete }}" == "true" ]]; then
+            echo "::error::terraform_delete cannot be used with code-deploy."
+            exit 1
+          fi
+          
   terraform-destroy:
-    #if: ${{ inputs.terraform_delete }}
-    if: >
-      ${{
-        inputs.terraform_delete &&
-        inputs.deploy != 'code-deploy'
-      }}
+    if: ${{ inputs.terraform_delete }}
+    needs: validate-inputs
     runs-on: ubuntu-latest
     steps:
       - run: |
@@ -31,7 +37,7 @@ jobs:
             #exit 1
             
   infra-deploy:
-    needs: terraform-destroy
+    needs: [ validate-inputs, terraform-destroy ]
     if: >
       always() &&
       (needs.terraform-destroy.result == 'success' || needs.terraform-destroy.result == 'skipped') &&
@@ -43,7 +49,7 @@ jobs:
           echo "Running infra deploy"
           #exit 1
   code-deploy:
-    needs: [terraform-destroy, infra-deploy]
+    needs: [validate-inputs, terraform-destroy, infra-deploy]
     if: >
       always() &&
       (needs.terraform-destroy.result == 'success' || needs.terraform-destroy.result == 'skipped') &&
